### ISSUE TITLE
Proposal: Truncate all labels to 50 characters

### ISSUE THREAD

**Issue by MattLewin** [jeffwidman/bitbucket-issue-migration#106]
While BitBucket apparently allows arbitrarily long strings for `component`, `kind` and `version`, GitHub allows a maximum of 50 characters in a label name.

In issue #105, I was slamming into this, and the script was crashing.

I propose we truncate labels to 50 characters. The resulting label will be created in GitHub, and the user can edit it afterward.

**Comment by jeffwidman** [comment]
Fixed in 69316a91c68fe5150486ec85e8cd3731731ab223 / https://github.com/jeffwidman/bitbucket-issue-migration/pull/107
