### ISSUE TITLE
Cannot install dependencies because venv tool deprecated.

### ISSUE THREAD

**Issue by topfeedca** [jeffwidman/bitbucket-issue-migration#116]
I am completely new to Python. I'm sure there's a simple answer for this issue. After succesfully installing Requests, I entered the following:

_**(py3) bash-3.2$ pyvenv ./py3**_

which resulted in:

_**WARNING: the pyenv script is deprecated in favour of `python3.7 -m venv`**_
_**(py3) bash-3.2$**_ 

So then I entered: 
_**python3.7 -m venv ./py3
source ./py3/bin/activate
pip3 install -r requirements.pip**_

Which results in this error:
_**Could not open requirements file: [Errno 2] No such file or directory: 'requirements.pip'**_

**Comment by jeffwidman** [comment]
That's a simple error showing that `pip3` can't find the file... nothing about compatibility. Give it the full folder path or `cd` to that folder when running the command and it should work fine.

I'm going to close, but if you are still hitting problems please comment and I'm happy to re-open.
