### ISSUE TITLE
KeyError assuming "username" key

### ISSUE THREAD

**Issue by reticulatedpines** [jeffwidman/bitbucket-issue-migration#122]
In April, Bitbucket changed their policy around usernames, which I assume changed the JSON format so "username" no longer exists:
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/

migrate.py assumes username exists in a few places with no error handling.  Here's the end of a stacktrace:
  File "./migrate.py", line 662, in format_user
    bb_user = "Bitbucket: [{0}](https://bitbucket.org/{0})".format(user['username'])
KeyError: 'username'

There is now a "nickname" field and "account_id".  BB APIs now use account_id where they would have used username, but I guess when importing to GH it makes more sense to use the nickname as a display name so maybe this isn't a completely trivial change.

**Comment by reticulatedpines** [comment]
Here's my quick hack "works for me" changes:

[hack_fix.txt](https://github.com/jeffwidman/bitbucket-issue-migration/files/3523291/hack_fix.txt)

Stuff that's not needed:
 - changing the env line to python3 (but, if python2 is your default interpreter, the current file is broken)
 - the keyring exception handling.  This was because I do have a keyring program installed, but it doesn't hold my Github creds.  Pressing Cancel triggered the exception with no way to manually enter my GH password

**Comment by rtoumazet** [comment]
Worked for me ... thanks !

**Comment by jeffwidman** [comment]
Fixed in https://github.com/jeffwidman/bitbucket-issue-migration/pull/119 (the earliest PR that submitted the fix)

My apologies for the delay here, simply didn't see the notifications (I've been unsubscribing from a bunch of repos so hopefully will see stuff like this more in the future)
