### ISSUE TITLE
Failed to POST due to unexpected HTTP status code: 410

### ISSUE THREAD

**Issue by lgautier** [jeffwidman/bitbucket-issue-migration#123]
Hi,

Thanks for making that code available. It would help me a lot to migrate mercurial repositories out of bitbucket before they are deleted.

However, I am running in to the following error at the the very first issue:
`RuntimeError: Failed to POST issue: '<issue name>' due to unexpected HTTP status code: 410`

A dry run with `-n` is working fine though.

**Comment by lgautier** [comment]
The issue was caused because the target github repository did not have/allow issue tracking. :man_facepalming:

**Comment by jeffwidman** [comment]
Thanks for circling back on this, it's appreciated.
