### ISSUE TITLE
Properly attribute comments to users

### ISSUE THREAD

**Issue by bzaar** [jeffwidman/bitbucket-issue-migration#131]
Currently we are getting the text "Original report by..." in every comment. Is there a way to make the comments appear as if they were added by specific GitHub users?

**Comment by bzaar** [comment]
Would it be possible if I had all of the users' passwords/tokens?

**Comment by jeffwidman** [comment]
I don't know. My guess is it's probably possible, but will require quite a bit of work (and a lot more API calls). And--as you said--you'd need tokens for all the users.

If you want to add support for it, I'd be happy to look at a PR, but if I were the product manager, I'd honestly question whether it was worth the value or not... unless you want to be able to search/filter by which users have commented on which tickets in the github web UI... Certainly useful, but once you're past the one-time migration that will become less and less valuable over time.

**Comment by bzaar** [comment]
Thanks for looking at this. It's certainly a lot less valuable for me now and I doubt anyone would pick up this task so I'm closing it for now.
