### ISSUE TITLE
Permission denied if issues are private

### ISSUE THREAD

**Issue by Yemeni** [jeffwidman/bitbucket-issue-migration#133]
If the repository is public on bitbucket but the issue tracking is private you will get a permission denied even after you have logged 
`
RuntimeError: Bitbucket login succeeded, but user 'Yemeni' doesn't have permission to access the url: https://api.bitbucket.org/2.0/repositories/Yemeni/repo/issues`

**Comment by jeffwidman** [comment]
I'd happily entertain a PR fixing this.

**Comment by magreenblatt** [comment]
This is working for me currently (export from public repository with private issue tracker). I created a Bitbucket app password with Repositories/Read and Issues/Read permissions only.

**Comment by jeffwidman** [comment]
Awesome, thanks for letting me know!
