### ISSUE TITLE
Bitbucket API currently broken, doesn't respect start/limit params, breaks '-f' option

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/bitbucket-issue-migration#32]
Reported here: https://github.com/jeffwidman/bitbucket_issue_migration/issues/20#issuecomment-153682091
> the problem with -f comes from Bitbucket's api that are broken, neither "start" nor "limit" work according to the docs. With 17 issues, if I pass -f 15 it copies the first 2 (=17-15) issues. Similarly, limit does not limit anything but it just takes the last X issues

@serviceman do you know if this is still an issue? 

I saw bitbucket rolled out v2 of their cloud apis--would switching to those fix this?

**Comment by serviceman** [comment]
I think I had tried with the "up-to-date" API (v2), and I was very surprised that the docs were really wrong. Surprised that it came from their side, Instead of me mistaking the docs with the API version. But again, that's all I remember: my big surprise

**Comment by jeffwidman** [comment]
Thanks--that is helpful since I was thinking that switching to v2 was the right move because that's where BB would be investing their time to fix stuff...  I'll keep an eye on it from time to time and see if they fix it

**Comment by jeffwidman** [comment]
I looked into this a bit, v1 supports the following url structure:
https://bitbucket.org/api/1.0/repositories/zzzeek/sqlalchemy/issues/?sort=local_id&start=1000
as documented here: https://confluence.atlassian.com/bitbucket/issues-resource-296095191.html#issuesResource-DELETEanissue
and the offset works. 

alternatively, v2 supports the following URL structure:
https://bitbucket.org/api/2.0/repositories/zzzeek/sqlalchemy/issues/?sort=id&page=10&pagelen=2
as partially documented here: https://confluence.atlassian.com/bitbucket/version-2-423626329.html

For v2, there's no working 'start' param that starts from an ID. We also can't just do some math to figure out a combo of `page` and `pagelen` that generates the correct offset because issues can be deleted... so if we want to start from issue #5, we aren't guaranteed that there are still 4 issues before it. 

However, v2 also includes extensive links within each payload, so we could say 'start from ID X' and just assume the user inputs a valid ID, and from there traverse through the issues one-by-one. 

See also comments on #30 about page-by-page vs issue-by-issue queries.
