### ISSUE TITLE
References to Github usernames might be wrong. (check if GH username 404's)

### ISSUE THREAD

**Issue by jaraco** [jeffwidman/bitbucket-issue-migration#46]
Consider [hgtools 30](https://github.com/jaraco/hgtools/issues/30). That ticket, migrated from bitbucket, indicates it was originally reported by https://github.com/laffoyb, but that URL returns a 404.

The migration script shouldn't be declaring a Github user based on naive inference. It should omit the Github link unless the script is provided with a username mapping. Otherwise, it creates broken or possibly erroneous links.

**Comment by jeffwidman** [comment]
Yeah, this one is a tough. 

Ideally we could retrieve the email address of the BB user and find the GH account associated with that email, but I'm not aware of any API endpoints that let us easily extract that info.

It is an easy fix to check if the GH user exists, and if it 404's to state that the GH handle of the user is unknown. 

Beyond that, I think it's better to include links using the naiive assumption that BB and GH urls are the same. While certainly not always a correct assumption, it is correct most of the time. The utility of having those links (even with the occasional incorrect one) is much higher than not having any links at all... which is what will happen most of the time if we require the user to generate a custom username mapping. 

I already had a note in the Readme mentioning this assumption, so the fix here is to just add the 404 check of the BB username.

**Comment by jaraco** [comment]
Agree on all points. One thing I considered was simple adding "guess" or "maybe" or "?" Indicating that it's not a verified match.

Another check might be to confirm that the full names or emails match... Even if the correct link cannot be detected, it's better to omit the link than provide an incorrect one.

Thanks for considering this.

**Comment by jeffwidman** [comment]
>One thing I considered was simple adding "guess" or "maybe" or "?" Indicating that it's not a verified match.

I'm in favor of this--we should be making this assumption explicit. The verbiage needs to be both clear and concise. Everything that I've experimented with feels either confusing or wordy. What do you think about "Github (best guess)" or "Github (unverified)" for the anchor text?

> Another check might be to confirm that the full names or emails match... 

Both of these aren't 100% accurate, so I wouldn't exclude the link even if they don't match. However, if they do match, then that's probably good enough that we don't need to mark the Github link as '(unverified)'.

Is there a relatively straightforward way to retrieve a user's email from BB and GH?

I'm not aware of one except by looking for a commit by the user, then checking the commit to see their email. Feels overly complicated to get an email this way just so we can remove '(unverified)'.

> Even if the correct link cannot be detected, it's better to omit the link than provide an incorrect one.

Absolutely, as long as we know for certain it's incorrect.
