### ISSUE TITLE
RuntimeError: Could not find the Bitbucket repository

### ISSUE THREAD

**Issue by benoror** [jeffwidman/bitbucket-issue-migration#57]
After fixing https://github.com/jeffwidman/bitbucket-issue-migration/pull/56 I got the following error

```
$ python3 migrate.py panaxit panax-cli panaxit panax-cli
Please enter your GitHub password.
Note: If your account has two-factor authentication enabled, you must use a personal access token from https://github.com/settings/tokens in place of a password for this script.

Traceback (most recent call last):
  File "migrate.py", line 435, in <module>
    sys.exit(main(options))
  File "migrate.py", line 109, in main
    issues = get_issues(bb_url, options.start)
  File "migrate.py", line 286, in get_issues
    .format(url=bb_url)
RuntimeError: Could not find the Bitbucket repository: https://api.bitbucket.org/1.0/repositories/panax-cli/issues
Hint: the Bitbucket repository name is case-sensitive.

```

**Comment by benoror** [comment]
Ok, after [fixing some typos](https://github.com/benoror/bitbucket-issue-migration/commit/aaa63ab3586b0f01392dd59cc3edf81cef4b19eb) I found the reason is that bitbucket's API returns status 403 Forbbiden for my public repo:

https://api.bitbucket.org/1.0/repositories/panaxit/panax-cli/issues

any idea why?

**Comment by benoror** [comment]
I think I misunderstood the instructions, for those wondering this is the expected format:

```
python3 migrate.py <bitbucket_username> <user or org>/<repo> <github_username> <user or org>/<repo>
```

**Comment by benoror** [comment]
Nevertheless, I'm still getting status 403 Forbbiden

**Comment by jeffwidman** [comment]
Hmm... I'll try and test it sometime this weekend. 

Did you test with any other BB public repos to see if they worked for you?

Also, if you think the readme could be better worded, feel free to submit a PR. I agree it's easy to confuse authentication username with user/org name of the repo.

**Comment by benoror** [comment]
thanks @jeffwidman, I've actually found another script:

https://github.com/siong1987/issues_importer

Although it's less robust, it does the job for my needs

Kind regards!

**Comment by jeffwidman** [comment]
I just tested this with several public repos, and it works fine. I attempted to test with your repo, but got the message that your BB repo was deleted. No idea what your problem was (other than the two typos)

**Comment by benoror** [comment]
Thanks, I probably misunderstood the instructions.
