### ISSUE TITLE
Error message when running script...

### ISSUE THREAD

**Issue by abadger1406** [jeffwidman/bitbucket-issue-migration#63]
{"error": {"message": "Resource not found", "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://confluence.atlassian.com/x/IYBGDQ"}}

**Comment by abadger1406** [comment]
python3 migrate.py abadger https://bitbucket.org/abadger/c2p abadger1406 https://github.com/NetFM/c2p
Please enter your Bitbucket password.

Please enter your GitHub password.
Note: If your account has two-factor authentication enabled, you must use a personal access token from https://github.com/settings/tokens in place of a password for this script.

Traceback (most recent call last):
  File "migrate.py", line 442, in <module>
    sys.exit(main(options))
  File "migrate.py", line 116, in main
    issues = get_issues(bb_url, options.start, bb_auth)
  File "migrate.py", line 182, in get_issues
    .format(bb_url)
RuntimeError: Could not find the Bitbucket repository: https://api.bitbucket.org/1.0/repositories/https://bitbucket.org/abadger/c2p/issues
Hint: the Bitbucket repository name is case-sensitive.
(py3) dave@dave-desktop:~/bitbucket-issue-migration$

**Comment by jeffwidman** [comment]
What is the full command that you're using to execute the script?

Is the BB repo public? If so, paste it here so I can test.

Most likely you're using an incorrect repo location in your options.

**Comment by jeffwidman** [comment]
You're entering the wrong options. Replace `https://bitbucket.org/abadger/c2p` with `abadger/c2p`

**Comment by abadger1406** [comment]
Thank you...making progress..


python3 migrate.py abadger abadger/c2p abadger1406 https://github.com/NetFM/c2p
Please enter your Bitbucket password.

Please enter your GitHub password.
Note: If your account has two-factor authentication enabled, you must use a personal access token from https://github.com/settings/tokens in place of a password for this script.

Traceback (most recent call last):
  File "migrate.py", line 442, in <module>
    sys.exit(main(options))
  File "migrate.py", line 131, in main
    gh_issue, gh_comments, options.github_repo, gh_auth, headers
  File "migrate.py", line 403, in push_github_issue
    .format(issue['title'], respo.status_code)
RuntimeError: Failed to POST issue: '7.1.1 Map View - Reservation Details' due to unexpected HTTP status code: 404
(py3) dave@dave-desktop:~/bitbucket-issue-migration$

**Comment by abadger1406** [comment]
No issues imported yet, there are 98 issues in total to import

**Comment by abadger1406** [comment]
The issue mentioned, looks fairly stanard, ability 5 comments and is resolved. It does have a # in the title...will try changing this.

**Comment by abadger1406** [comment]
Looks like it just fails on first issue, changed title to 'issue 1'

python3 migrate.py abadger abadger/c2p abadger1406 https://github.com/NetFM/c2p
Please enter your Bitbucket password.

Please enter your GitHub password.
Note: If your account has two-factor authentication enabled, you must use a personal access token from https://github.com/settings/tokens in place of a password for this script.

Traceback (most recent call last):
  File "migrate.py", line 442, in <module>
    sys.exit(main(options))
  File "migrate.py", line 131, in main
    gh_issue, gh_comments, options.github_repo, gh_auth, headers
  File "migrate.py", line 403, in push_github_issue
    .format(issue['title'], respo.status_code)
RuntimeError: Failed to POST issue: 'issue 1' due to unexpected HTTP status code: 404
(py3) dave@dave-desktop:~/bitbucket-issue-migration$

**Comment by jeffwidman** [comment]
This is going to fail for the same reason as the BB url... did you read the Readme?
