### ISSUE TITLE
First issue gets copied...then assert error

### ISSUE THREAD

**Issue by abadger1406** [jeffwidman/bitbucket-issue-migration#64]
python3 migrate.py abadger abadger/c2p abadger1406 NetFM/c2p
Please enter your Bitbucket password.

Please enter your GitHub password.
Note: If your account has two-factor authentication enabled, you must use a personal access token from https://github.com/settings/tokens in place of a password for this script.

Imported Issue: https://api.github.com/repos/NetFM/c2p/issues/12
Traceback (most recent call last):
  File "migrate.py", line 442, in <module>
    sys.exit(main(options))
  File "migrate.py", line 148, in main
    assert gh_issue_id == issue['local_id']
AssertionError

When I look at github, it has just the first issue copied. This issue will get repeated if I run again, but no new issues beyond this are copied.

**Comment by abadger1406** [comment]
The repository is part of NetFM organisation, maybe this is related to this issue

**Comment by abadger1406** [comment]
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

Is error message on url above

**Comment by jeffwidman** [comment]
This is because of #42 - I added a test that catches the issue (and that test is failing on your second issue here), but haven't yet added a workaround for the issue. 

What's the BB url of the repo you're trying to migrate?

**Comment by abadger1406** [comment]
https://github.com/NetFM/c2p

I've made it public so you can see the repeated issue that has been copied
