### ISSUE TITLE
start option is poorly named

### ISSUE THREAD

**Issue by jaraco** [jeffwidman/bitbucket-issue-migration#76]
The name of the start option suggests that it's an issue number from which to start, when it's actually an offset to skip past. Although computer scientists hold it as a badge of honor to start numbering with zero, but when the issues are numbered starting with 1, the interface for the issue migration should do the same. Start should indicate the first issue to be processed or it should be renamed to something like "skip" or "offset".

**Comment by jeffwidman** [comment]
Good point. At first glance, I'm open to either incrementing start by 1 under the covers or renaming... PR welcome.
