### ISSUE TITLE
Only works on public issues/repositories on bitbucket

### ISSUE THREAD

**Issue by rafdizzle86** [jeffwidman/bitbucket-issue-migration#8]
Just a comment, not really an issue - this only works on issue trackers that are public in bitbucket, otherwise you'll get an HTTP error and the migration will fail.

**Comment by jeffwidman** [comment]
#22 tackles this. Waiting for it to be rebased before merging.

**Comment by jeffwidman** [comment]
If a user submits BB creds, but the BB repo is public, then we shouldn't worry about whether the user's BB creds are authentic, we should just use the public API to grab the issues without authenticating.

So probably the workflow is:
 - regardless of whether the user provided BB creds, we should try the BB repo without auth
 - only if we get back a 401 do we check for BB auth creds--if the user didn't include them, then complain
 - if the user included BB auth creds, and we already know it's not a public repo, then we try again to access it
- if we still get a 404 or 401, complain appropriately to the user

**Comment by jeffwidman** [comment]
Fixed in #59
