### ISSUE TITLE
Issue migration does not migrate images in the issue

### ISSUE THREAD

**Issue by nicholasli137** [jeffwidman/bitbucket-issue-migration#83]
While migrating issues to GitHub, looks like it does not migrate images in the issue.

**Comment by jeffwidman** [comment]
1) If the repo is public, can you link to the issue in both BB and GH so we can see what it was originally and then what it became?

2) What is the GitHub issue actually showing? A broken image icon? 

3) If you try to edit the github issue, did the html embed code come across properly?

**Comment by nicholasli137** [comment]
Since both repos are private, I am gonna show markdown code for the comments on the both.

```
*Original comment by* **Jonathon (Bitbucket: [JonPod](https://bitbucket.org/JonPod), GitHub: Unknown)**:

----------------------------------------

![what are.png](https://bitbucket.org/repo/KEMxRo/images/3458064200-what%20are.png)

```

![image](https://cloud.githubusercontent.com/assets/15174762/22873040/5282157e-f18b-11e6-95ec-b59078fa6a42.png)


I think it is related to permissions. You're right.

**Comment by jeffwidman** [comment]
Sounds good, thanks for following up.
