### ISSUE TITLE
Issues with some labels are migrated as `Closed`

### ISSUE THREAD

**Issue by nicholasli137** [jeffwidman/bitbucket-issue-migration#84]
The issues with labels `on hold`, `resolved` are migrated as `closed` even if there are not closed on BitBucket.

**Comment by jeffwidman** [comment]
If the repo's being migrated are public, can you link to both the source and dest repo?

**Comment by jeffwidman** [comment]
Relevant code is likely here: https://github.com/jeffwidman/bitbucket-issue-migration/commit/8dd61a361c20b6b0e3816181b5a662f804625633#diff-9436d08f8a9a7146dda153bc5f0c8943R303

In BB, issues have both labels and status. The status determines whether it's marked as closed, irrespective of the issue label.

What is the status that BB is reporting for these issues?

**Comment by nicholasli137** [comment]
Thanks @jeffwidman.
Yeah, it's status not label.
I believe `ON HOLD` issues are migrated as `closed`.
Looks like `OPEN`, `NEW` issues are migrated as `open`.
And the all the others are migrated as `closed`.

**Comment by jeffwidman** [comment]
Thanks for the details. AFAIK, GitHub only supports open/closed for status. 

I will add `On Hold` as `open`, although `resolved` seems like it fits better with `closed` than `open`.

**Comment by jeffwidman** [comment]
@nicholasli137 can you try the latest version and see if it fixes it for you?

**Comment by nicholasli137** [comment]
Thank you so much @jeffwidman 
I believe it is fixed. :+1:
