### ISSUE TITLE
Errors if the github repo already has issues

### ISSUE THREAD

**Issue by GeorgeFuller** [jeffwidman/bitbucket-issue-migration#90]
Imported Issue: https://api.github.com/repos/****/****/issues/7
Traceback (most recent call last):
  File "migrate.py", line 608, in <module>
    sys.exit(main(options))
  File "migrate.py", line 205, in main
    assert gh_issue_id == issue['local_id']
AssertionError

Received this error when running the script. I fixed it by making a new github repo that didn't already have issues in it. Guess it doesn't work if your repo already has issues.

**Comment by jeffwidman** [comment]
This is documented in the readme.
