### ISSUE TITLE
Add a bit better explanation for -n key

### ISSUE THREAD

**Issue by dmitriy-t** [jeffwidman/bitbucket-issue-migration#97]
May be it is worth to add a bit more descriptive help line for "-n" key? 
Like "Perform a dry run: issues transfer will be only simulated, no data will be copied. You would be able to see all your Bitbucket issues and whether they can be transferred to GitHub". Something like that.
By the way, thank you for a great tool!

**Comment by jeffwidman** [comment]
Great idea, want to submit a pull request?

Don't put "whether they can be transferred to GitHub" because dry-run doesn't fully test GH submission, it only tests bitbucket extraction and conversion up to (but not including) the point of submitting to GH.

**Comment by dmitriy-t** [comment]
Hi, I can do it, but, unfortunately, only in a couple of days (so, you can fix it yourself if you wish).

**Comment by jeffwidman** [comment]
Fixed by #104
