### ISSUE TITLE
Does this close the Bitbucket issues?

### ISSUE THREAD

**Issue by nedbat** [jeffwidman/bitbucket-issue-migration#99]
The README says it closes the issues on Bitbucket, but I didn't see that in the code.  I'd like to try this out to see what the resulting GitHub issues look like, but not close the Bitbucket issues yet.

**Comment by nedbat** [comment]
Oh, now I understand.  The README means that the newly created GitHub issues will be closed, if the original Bitbucket issue is closed.

**Comment by jeffwidman** [comment]
You got it. BTW, I was both educated and entertained by your machete mode debugging talk, thanks for putting the time into it.

**Comment by nedbat** [comment]
Thanks! BTW, I'm working on some changes to the tool, I'll make a few pull requests.
